### ISSUE TITLE
Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Azure.WebJobs.IWebJobsBuilder.get_Services()'.

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker-preview#13] opened 2020-12-11 19:29 UTC
If you get this error, it's because you have a (possibly transitive) reference to `Microsoft.Extensions.DepenencyInjection.Abstractions` 5.0.0. 

Workaround; Explicitly reference v3.1 of this package in your project.

The issue with the host has been checked-in here; https://github.com/Azure/azure-functions-host/pull/6971 but won't be available in production for several weeks.

**Comment by ngg** [comment] 2020-12-11 20:15
Can you please explain why does having a "wrong version" package can cause issues? I thought the whole idea of moving the worker out-of-process was to avoid exactly these types of problems, like we had before when trying to use a version of ApplicationInsights, Logging or SqlClient that didn't match the version the host depended on.

**Comment by brettsam** [comment] 2020-12-11 20:32
Good catch :-).

We're currently using C# Source Generators to create the function metadata and compile it into your output assembly (so there's no need for function.json). The host then loads that assembly and reads the metadata instead of looking for a function.json -- and that's it, it doesn't actually run anything else.

The end goal is to make the output look and feel a lot more like a standard .NET application rather than the way it looks today with all the assemblies under /bin and folders containing function.json files.

It's a very narrow scenario and only used at startup time to read the metadata. It needs to redirect a few abstraction-level types like this back to 3.1 for that load but your worker will be running in .NET 5 in a separate process. We're hoping we can make it run smoothly enough that you don't need to think about it. But we missed the redirect on this assembly in the host. We will have a fallback mode but it's not yet implemented.

We'd love feedback on this approach. We've bumped into issues with VS tooling and some of our more complicated build tasks with our project structure in current .NET apps that we're trying to make the build and tooling experience more straightforward wherever we can.

**Comment by ngg** [comment] 2020-12-11 20:58
Thanks for the explanation!

I'm sure you've thought this through, but why cannot the metadata generator simply produce a function.json file that can be used by the host? That way the worker and the host could be fully separated but the bindings would be still conveniently auto-generated. For example if some kind of native AOT will be implemented in .NET 6 actually producing native binaries, those will probably be unloadable as assemblise in the host, but the simple json-based solution could still work.

**Comment by fabiocav** [comment] 2020-12-11 21:00
Worth noting that this entirely a "point in time" issue. The host will be supporting a contract with the worker that will eliminate the dependency on the file system layout and metadata files. This will be present in future updates and there will be no strict dependency on loading assemblies produced by the project.

**Comment by Spaceman1861** [comment] 2020-12-16 13:04
I had a similar issue I had to reference an older of cosmos db ef core packages.

**Comment by rubo** [comment] 2020-12-24 02:24
> Workaround; Explicitly reference v3.1 of this package in your project.

If any other project dependency references Microsoft.Extensions.DepenencyInjection.Abstractions v5 directly or indirectly, the workaround is not possible.

**Comment by mwwhited** [comment] 2020-12-24 09:11
Why not stick with the function.JSON and just do an out of process call like you do with other languages? Or just generate a csx bridge using the .net 5 library and the functions.json

**Comment by Mithras** [comment] 2021-01-04 19:14
Is there an estimate for a fix?

**Comment by swasun99** [comment] 2021-01-08 22:20
We are trying to use global start up with the .net 5 azure function worker and facing the same issue. Is anyone else able to add a global start up successfully without running into this error?

**Comment by shibayan** [comment] 2021-01-10 14:56
I am not happy with the error caused by the assembly of azure-functions-host, even though it is supposed to be an isolated environment. Since downgrading assembly versions is not possible in Entity Framework Core, etc., I believe a fundamental fix is needed.

It is already known that this can be resolved by upgrading the `Microsoft.Extensions.*` referenced by azure-functions-host to 5.0.0. However, it is very understandable to be cautious about doing so because of the wide range of effects.

So, my suggestion is that since `Microsoft.Extensions.*` has an `Abstractions` package that only defines interfaces, updating only that package to 5.0.0 would minimize the impact on existing implementations.

I checked the following branch, and it worked fine for my function. Of course, there was no problem even when referring to packages such as Entity Framework Core 5.0.
https://github.com/Azure/azure-functions-host/compare/dev...shibayan:add-abstractions-5.0

I hope this helps.

**Comment by fabiocav** [comment] 2021-01-29 02:40
Closing this as resolved in preview 3

**Closed by fabiocav** 2021-01-29 02:40 UTC
